[package]
name = "primp-python"
version = "2.0.0"
edition = "2021"
rust-version = "1.89"
description = "HTTP client that can impersonate web browsers"
authors = ["deedy5"]
license = "MIT"

[lib]
name = "primp"
path = "src/lib.rs"
crate-type = ["cdylib"]
doc = false

[dependencies]
pyo3 = { version = "0.29", features = ["abi3-py310", "indexmap", "anyhow", "multiple-pymethods"] }
pyo3-async-runtimes = { version = "0.29", features = ["tokio-runtime"] }
anyhow = "1.0.104"
tracing = { version = "0.1.41", features = ["log-always"] }
pyo3-log = "0.13.2"
log = "0.4"
primp = { version = "2.0", path = "../primp", features = [
    "hickory-dns",
] }
bytes = "1"
encoding_rs = { version = "0.8.35" }
foldhash = "0.2.0"

indexmap = { version = "2.13.0", features = ["serde"] }
tokio = { version = "1.49.0", features = ["full"] }
tokio-util = { version = "0.7.18", features = ["codec"] }  # for multipart
html2text = "0.17"
pythonize = "0.29"
serde_json = "1.0.149"
jiter = { version = "0.16", features = ["python"] }
http = "1.4"
mime = "0.3.17"
rand = "0.10"
url = "2.5"

[dev-dependencies]
tempfile = "3"

